# Generated by Django 3.0.1 on 2020-01-17 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantones',
            fields=[
                ('id_canton', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cantón',
                'verbose_name_plural': 'Cantones',
            },
        ),
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('id_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('puntosReferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Fase_lunar',
            fields=[
                ('id_fase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Fase lunar',
                'verbose_name_plural': 'Fases lunares',
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id_periodos', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.TimeField()),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Indique el rol', max_length=25)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Tipo_oleaje',
            fields=[
                ('id_tipo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de oleaje',
                'verbose_name_plural': 'Tipos de oleajes',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cedula', models.CharField(blank=True, max_length=15, null=True)),
                ('auth_user', models.OneToOneField(db_column='auth_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Estados')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Provincias')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Roles')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Parroquias',
            fields=[
                ('id_parroquia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Cantones')),
            ],
            options={
                'verbose_name': 'Parróquia',
                'verbose_name_plural': 'Parróquias',
            },
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('epoca', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('registeredto', models.DateTimeField()),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Estaciones')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Estados')),
                ('id_fase_lunar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Fase_lunar')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Usuarios')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id_medicion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('corriente_resaca', models.BooleanField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('perfil_playa', models.IntegerField()),
                ('ancho_zon_surf', models.FloatField()),
                ('lp_flotador', models.IntegerField()),
                ('lp_rompiente', models.IntegerField()),
                ('crl_espacio', models.FloatField()),
                ('crl_tiempo', models.IntegerField()),
                ('crl_velocidad', models.FloatField()),
                ('crl_direccion', models.CharField(max_length=1)),
                ('vien_direccion', models.IntegerField()),
                ('vien_velocidad', models.FloatField()),
                ('ola_ortogonal', models.IntegerField()),
                ('ola_periodo_onda', models.IntegerField()),
                ('ola_altura_rompiente_promedio', models.FloatField()),
                ('ola_direccion', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caracteristicas.Estados')),
                ('id_observacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caracteristicas.Observaciones')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caracteristicas.Periodos')),
                ('ola_tipo_oleaje', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caracteristicas.Tipo_oleaje')),
            ],
            options={
                'verbose_name': 'Medicion',
                'verbose_name_plural': 'Mediciones',
            },
        ),
        migrations.AddField(
            model_name='estaciones',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Estados'),
        ),
        migrations.AddField(
            model_name='estaciones',
            name='id_parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Parroquias'),
        ),
        migrations.AddField(
            model_name='cantones',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caracteristicas.Provincias'),
        ),
        migrations.CreateModel(
            name='Altura_rompiente',
            fields=[
                ('id_alt_romp', models.AutoField(primary_key=True, serialize=False)),
                ('num_medicion', models.IntegerField()),
                ('valor', models.FloatField()),
                ('id_medicion', models.ForeignKey(db_column='id_medicion', on_delete=django.db.models.deletion.DO_NOTHING, to='caracteristicas.Mediciones')),
            ],
            options={
                'verbose_name': 'Altura rompiente',
                'verbose_name_plural': 'Alturas rompientes',
            },
        ),
    ]
