INSERT INTO caracteristicas_fase_lunar(nombre) VALUES('Cuadratura');
INSERT INTO caracteristicas_fase_lunar(nombre) VALUES('Sicigia');
insert into caracteristicas_periodos(horario)	values('07:00');
insert into caracteristicas_periodos(horario)	values('07:30');
insert into caracteristicas_periodos(horario)	values('08:00');
insert into caracteristicas_periodos(horario)	values('08:30');
insert into caracteristicas_periodos(horario)	values('09:00');
insert into caracteristicas_periodos(horario)	values('09:30');
insert into caracteristicas_periodos(horario)	values('10:00');
insert into caracteristicas_periodos(horario)	values('10:30');
insert into caracteristicas_periodos(horario)	values('11:00');
insert into caracteristicas_periodos(horario)	values('11:30');
insert into caracteristicas_periodos(horario)	values('12:00');
insert into caracteristicas_periodos(horario)	values('12:30');
insert into caracteristicas_periodos(horario)	values('13:00');
insert into caracteristicas_periodos(horario)	values('13:30');
insert into caracteristicas_periodos(horario)	values('14:00');
insert into caracteristicas_periodos(horario)	values('14:30');
insert into caracteristicas_periodos(horario)	values('15:00');
insert into caracteristicas_periodos(horario)	values('15:30');
insert into caracteristicas_periodos(horario)	values('16:00');
insert into caracteristicas_periodos(horario)	values('16:30');
insert into caracteristicas_periodos(horario)	values('17:00');
insert into caracteristicas_periodos(horario)	values('17:30');
insert into caracteristicas_periodos(horario)	values('18:00');
insert into caracteristicas_periodos(horario)	values('18:30');
INSERT INTO caracteristicas_tipo_oleaje(id_tipo, nombre) VALUES('spi', 'Spilling');
INSERT INTO caracteristicas_tipo_oleaje(id_tipo, nombre) VALUES('plu', 'Plunging');
INSERT INTO caracteristicas_tipo_oleaje(id_tipo, nombre) VALUES('s-p', 'Spilling-Plunging');
INSERT INTO caracteristicas_tipo_oleaje(id_tipo, nombre) VALUES('coll', 'Collopsing');
INSERT INTO caracteristicas_tipo_oleaje(id_tipo, nombre) VALUES('sur', 'Surging');
